[package]
name = "mrs-benchmark-core"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
glam = { version = "0.28", default-features = false, features = ["libm"] }
nalgebra = { version = "0.33", default-features = false, features = ["libm"] }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }


